### ISSUE TITLE
does this still have pathplanner support in 2023?

### ISSUE THREAD

**Issue by brandonzx3** [jsimpso81/WPIlibMathLabVIEW#120]

**Comment by jsimpso81** [comment]
The PathPlanner LabVIEW project was moved to a separate repository in order to make this repository specific to implementing the Math section of WPILIB.

The PathPlanner LabVIEW project is here.   https://github.com/jsimpso81/PathPlannerLabVIEW    I need to make to add the old release.   However --- this has not been updated with the changes made this year to PathPlaner.  

The pathplanner utility should be able to export a WPILIB compatible trajectory JSON file.  This can be used by the WPILIB LabVIEW Math library.    Also there is a WPILIB LabVIEW Math trajectory creation routine that includes a lot of additional features beyond what PathWeaver has -- mostly constraints.   In other words the functionality provided by the WPILIB LabVIEW Math library and its utilities should provide similar functionality to pathplanner.  

It is a considerable effort to go through the changes made to pathplanner and port them again to LabVIEW.  While I may consider doing this, I think that concentrating on the main WPILIB LabVIEW math library and PhotonVision LabVIEW made more sense.   (As before if you or your team want to take this on, that would be great.)   Unlike the PhotonVision to Labview port, the amount of code that could run on the robot is much more substantial.   (Much simpler to export pathplanner paths as wpilib json files or use the WPILIB LabVIEW math tools instead.

The pathplanner library is here.
https://github.com/jsimpso81/PathPlannerLabVIEW
